# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'KServices_Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'KServices' ,  :path => '../'

  # Pods for KServices_Example

end
