use_frameworks!

platform :ios, '10.0'

target 'KServices_Example' do
  pod 'KServices', :path => '../'

  target 'KServices_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
